[project]
name = "reddit-clone-qa"
revision = "1.0"

[profiles.default]
FACTORY_DAGGER_RUNNER_HOST = { description = "Trusted Factory Dagger runner URI", required = true }

[scopes.qualification]
secrets = ["FACTORY_DAGGER_RUNNER_HOST"]
